/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as FairnessRouteImport } from './routes/fairness'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as BoardsIdRouteImport } from './routes/boards.$id'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors.index'
import { Route as ConnectorsMappingRouteImport } from './routes/connectors.mapping'
import { Route as DashboardHrRouteImport } from './routes/dashboard.hr'
import { Route as DashboardManagerRouteImport } from './routes/dashboard.manager'
import { Route as DashboardOwnerRouteImport } from './routes/dashboard.owner'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsThreadIdRouteImport } from './routes/insights.$threadId'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginOtpRouteImport } from './routes/login.otp'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as MePreferencesRouteImport } from './routes/me.preferences'
import { Route as MeRecognitionsRouteImport } from './routes/me.recognitions'
import { Route as MeRedeemRouteImport } from './routes/me.redeem'
import { Route as MeShoutoutRouteImport } from './routes/me.shoutout'
import { Route as MeTrackingRouteImport } from './routes/me.tracking'
import { Route as MeWalletRouteImport } from './routes/me.wallet'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsIdIndexRouteImport } from './routes/workflows.$id.index'
import { Route as WorkflowsIdRunsRouteImport } from './routes/workflows.$id.runs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const FairnessRoute = FairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIdRoute = BoardsIdRouteImport.update({
  id: '/boards/$id',
  path: '/boards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectorsRoute,
} as any)
const ConnectorsMappingRoute = ConnectorsMappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => ConnectorsRoute,
} as any)
const DashboardHrRoute = DashboardHrRouteImport.update({
  id: '/dashboard/hr',
  path: '/dashboard/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManagerRoute = DashboardManagerRouteImport.update({
  id: '/dashboard/manager',
  path: '/dashboard/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOwnerRoute = DashboardOwnerRouteImport.update({
  id: '/dashboard/owner',
  path: '/dashboard/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsThreadIdRoute = InsightsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => InsightsRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginOtpRoute = LoginOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => LoginRoute,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const MePreferencesRoute = MePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => MeRoute,
} as any)
const MeRecognitionsRoute = MeRecognitionsRouteImport.update({
  id: '/recognitions',
  path: '/recognitions',
  getParentRoute: () => MeRoute,
} as any)
const MeRedeemRoute = MeRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => MeRoute,
} as any)
const MeShoutoutRoute = MeShoutoutRouteImport.update({
  id: '/shoutout',
  path: '/shoutout',
  getParentRoute: () => MeRoute,
} as any)
const MeTrackingRoute = MeTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => MeRoute,
} as any)
const MeWalletRoute = MeWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => MeRoute,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdIndexRoute = WorkflowsIdIndexRouteImport.update({
  id: '/workflows/$id/',
  path: '/workflows/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRunsRoute = WorkflowsIdRunsRouteImport.update({
  id: '/workflows/$id/runs',
  path: '/workflows/$id/runs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/budget': typeof BudgetRoute
  '/campaigns': typeof CampaignsRoute
  '/capture': typeof CaptureRoute
  '/compliance': typeof ComplianceRoute
  '/connectors': typeof ConnectorsRouteWithChildren
  '/copilot': typeof CopilotRoute
  '/design-system': typeof DesignSystemRoute
  '/fairness': typeof FairnessRoute
  '/insights': typeof InsightsRouteWithChildren
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/payroll': typeof PayrollRoute
  '/people': typeof PeopleRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/insights': typeof ApiInsightsRoute
  '/boards/$id': typeof BoardsIdRoute
  '/connectors/mapping': typeof ConnectorsMappingRoute
  '/dashboard/hr': typeof DashboardHrRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/insights/$threadId': typeof InsightsThreadIdRoute
  '/login/otp': typeof LoginOtpRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/recognitions': typeof MeRecognitionsRoute
  '/me/redeem': typeof MeRedeemRoute
  '/me/shoutout': typeof MeShoutoutRoute
  '/me/tracking': typeof MeTrackingRoute
  '/me/wallet': typeof MeWalletRoute
  '/boards/': typeof BoardsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/me/': typeof MeIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRoute
  '/workflows/$id/': typeof WorkflowsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/budget': typeof BudgetRoute
  '/campaigns': typeof CampaignsRoute
  '/capture': typeof CaptureRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/design-system': typeof DesignSystemRoute
  '/fairness': typeof FairnessRoute
  '/kiosk': typeof KioskRoute
  '/onboarding': typeof OnboardingRoute
  '/payroll': typeof PayrollRoute
  '/people': typeof PeopleRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/insights': typeof ApiInsightsRoute
  '/boards/$id': typeof BoardsIdRoute
  '/connectors/mapping': typeof ConnectorsMappingRoute
  '/dashboard/hr': typeof DashboardHrRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/insights/$threadId': typeof InsightsThreadIdRoute
  '/login/otp': typeof LoginOtpRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/recognitions': typeof MeRecognitionsRoute
  '/me/redeem': typeof MeRedeemRoute
  '/me/shoutout': typeof MeShoutoutRoute
  '/me/tracking': typeof MeTrackingRoute
  '/me/wallet': typeof MeWalletRoute
  '/boards': typeof BoardsIndexRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/login': typeof LoginIndexRoute
  '/me': typeof MeIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRoute
  '/workflows/$id': typeof WorkflowsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/budget': typeof BudgetRoute
  '/campaigns': typeof CampaignsRoute
  '/capture': typeof CaptureRoute
  '/compliance': typeof ComplianceRoute
  '/connectors': typeof ConnectorsRouteWithChildren
  '/copilot': typeof CopilotRoute
  '/design-system': typeof DesignSystemRoute
  '/fairness': typeof FairnessRoute
  '/insights': typeof InsightsRouteWithChildren
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/payroll': typeof PayrollRoute
  '/people': typeof PeopleRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/insights': typeof ApiInsightsRoute
  '/boards/$id': typeof BoardsIdRoute
  '/connectors/mapping': typeof ConnectorsMappingRoute
  '/dashboard/hr': typeof DashboardHrRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/insights/$threadId': typeof InsightsThreadIdRoute
  '/login/otp': typeof LoginOtpRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/recognitions': typeof MeRecognitionsRoute
  '/me/redeem': typeof MeRedeemRoute
  '/me/shoutout': typeof MeShoutoutRoute
  '/me/tracking': typeof MeTrackingRoute
  '/me/wallet': typeof MeWalletRoute
  '/boards/': typeof BoardsIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/me/': typeof MeIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRoute
  '/workflows/$id/': typeof WorkflowsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/budget'
    | '/campaigns'
    | '/capture'
    | '/compliance'
    | '/connectors'
    | '/copilot'
    | '/design-system'
    | '/fairness'
    | '/insights'
    | '/kiosk'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/payroll'
    | '/people'
    | '/rewards'
    | '/settings'
    | '/whatsapp'
    | '/api/insights'
    | '/boards/$id'
    | '/connectors/mapping'
    | '/dashboard/hr'
    | '/dashboard/manager'
    | '/dashboard/owner'
    | '/insights/$threadId'
    | '/login/otp'
    | '/me/preferences'
    | '/me/recognitions'
    | '/me/redeem'
    | '/me/shoutout'
    | '/me/tracking'
    | '/me/wallet'
    | '/boards/'
    | '/connectors/'
    | '/insights/'
    | '/login/'
    | '/me/'
    | '/workflows/'
    | '/workflows/$id/runs'
    | '/workflows/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/budget'
    | '/campaigns'
    | '/capture'
    | '/compliance'
    | '/copilot'
    | '/design-system'
    | '/fairness'
    | '/kiosk'
    | '/onboarding'
    | '/payroll'
    | '/people'
    | '/rewards'
    | '/settings'
    | '/whatsapp'
    | '/api/insights'
    | '/boards/$id'
    | '/connectors/mapping'
    | '/dashboard/hr'
    | '/dashboard/manager'
    | '/dashboard/owner'
    | '/insights/$threadId'
    | '/login/otp'
    | '/me/preferences'
    | '/me/recognitions'
    | '/me/redeem'
    | '/me/shoutout'
    | '/me/tracking'
    | '/me/wallet'
    | '/boards'
    | '/connectors'
    | '/insights'
    | '/login'
    | '/me'
    | '/workflows'
    | '/workflows/$id/runs'
    | '/workflows/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/approvals'
    | '/budget'
    | '/campaigns'
    | '/capture'
    | '/compliance'
    | '/connectors'
    | '/copilot'
    | '/design-system'
    | '/fairness'
    | '/insights'
    | '/kiosk'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/payroll'
    | '/people'
    | '/rewards'
    | '/settings'
    | '/whatsapp'
    | '/api/insights'
    | '/boards/$id'
    | '/connectors/mapping'
    | '/dashboard/hr'
    | '/dashboard/manager'
    | '/dashboard/owner'
    | '/insights/$threadId'
    | '/login/otp'
    | '/me/preferences'
    | '/me/recognitions'
    | '/me/redeem'
    | '/me/shoutout'
    | '/me/tracking'
    | '/me/wallet'
    | '/boards/'
    | '/connectors/'
    | '/insights/'
    | '/login/'
    | '/me/'
    | '/workflows/'
    | '/workflows/$id/runs'
    | '/workflows/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BudgetRoute: typeof BudgetRoute
  CampaignsRoute: typeof CampaignsRoute
  CaptureRoute: typeof CaptureRoute
  ComplianceRoute: typeof ComplianceRoute
  ConnectorsRoute: typeof ConnectorsRouteWithChildren
  CopilotRoute: typeof CopilotRoute
  DesignSystemRoute: typeof DesignSystemRoute
  FairnessRoute: typeof FairnessRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  KioskRoute: typeof KioskRoute
  LoginRoute: typeof LoginRouteWithChildren
  MeRoute: typeof MeRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PayrollRoute: typeof PayrollRoute
  PeopleRoute: typeof PeopleRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  WhatsappRoute: typeof WhatsappRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  BoardsIdRoute: typeof BoardsIdRoute
  DashboardHrRoute: typeof DashboardHrRoute
  DashboardManagerRoute: typeof DashboardManagerRoute
  DashboardOwnerRoute: typeof DashboardOwnerRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  WorkflowsIdRunsRoute: typeof WorkflowsIdRunsRoute
  WorkflowsIdIndexRoute: typeof WorkflowsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairness': {
      id: '/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof FairnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$id': {
      id: '/boards/$id'
      path: '/boards/$id'
      fullPath: '/boards/$id'
      preLoaderRoute: typeof BoardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof ConnectorsRoute
    }
    '/connectors/mapping': {
      id: '/connectors/mapping'
      path: '/mapping'
      fullPath: '/connectors/mapping'
      preLoaderRoute: typeof ConnectorsMappingRouteImport
      parentRoute: typeof ConnectorsRoute
    }
    '/dashboard/hr': {
      id: '/dashboard/hr'
      path: '/dashboard/hr'
      fullPath: '/dashboard/hr'
      preLoaderRoute: typeof DashboardHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manager': {
      id: '/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof DashboardManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/owner': {
      id: '/dashboard/owner'
      path: '/dashboard/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof DashboardOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/$threadId': {
      id: '/insights/$threadId'
      path: '/$threadId'
      fullPath: '/insights/$threadId'
      preLoaderRoute: typeof InsightsThreadIdRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/otp': {
      id: '/login/otp'
      path: '/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof LoginOtpRouteImport
      parentRoute: typeof LoginRoute
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/preferences': {
      id: '/me/preferences'
      path: '/preferences'
      fullPath: '/me/preferences'
      preLoaderRoute: typeof MePreferencesRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/recognitions': {
      id: '/me/recognitions'
      path: '/recognitions'
      fullPath: '/me/recognitions'
      preLoaderRoute: typeof MeRecognitionsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/redeem': {
      id: '/me/redeem'
      path: '/redeem'
      fullPath: '/me/redeem'
      preLoaderRoute: typeof MeRedeemRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/shoutout': {
      id: '/me/shoutout'
      path: '/shoutout'
      fullPath: '/me/shoutout'
      preLoaderRoute: typeof MeShoutoutRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/tracking': {
      id: '/me/tracking'
      path: '/tracking'
      fullPath: '/me/tracking'
      preLoaderRoute: typeof MeTrackingRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/wallet': {
      id: '/me/wallet'
      path: '/wallet'
      fullPath: '/me/wallet'
      preLoaderRoute: typeof MeWalletRouteImport
      parentRoute: typeof MeRoute
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id/': {
      id: '/workflows/$id/'
      path: '/workflows/$id'
      fullPath: '/workflows/$id/'
      preLoaderRoute: typeof WorkflowsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id/runs': {
      id: '/workflows/$id/runs'
      path: '/workflows/$id/runs'
      fullPath: '/workflows/$id/runs'
      preLoaderRoute: typeof WorkflowsIdRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConnectorsRouteChildren {
  ConnectorsMappingRoute: typeof ConnectorsMappingRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
}

const ConnectorsRouteChildren: ConnectorsRouteChildren = {
  ConnectorsMappingRoute: ConnectorsMappingRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
}

const ConnectorsRouteWithChildren = ConnectorsRoute._addFileChildren(
  ConnectorsRouteChildren,
)

interface InsightsRouteChildren {
  InsightsThreadIdRoute: typeof InsightsThreadIdRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsThreadIdRoute: InsightsThreadIdRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface LoginRouteChildren {
  LoginOtpRoute: typeof LoginOtpRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginOtpRoute: LoginOtpRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface MeRouteChildren {
  MePreferencesRoute: typeof MePreferencesRoute
  MeRecognitionsRoute: typeof MeRecognitionsRoute
  MeRedeemRoute: typeof MeRedeemRoute
  MeShoutoutRoute: typeof MeShoutoutRoute
  MeTrackingRoute: typeof MeTrackingRoute
  MeWalletRoute: typeof MeWalletRoute
  MeIndexRoute: typeof MeIndexRoute
}

const MeRouteChildren: MeRouteChildren = {
  MePreferencesRoute: MePreferencesRoute,
  MeRecognitionsRoute: MeRecognitionsRoute,
  MeRedeemRoute: MeRedeemRoute,
  MeShoutoutRoute: MeShoutoutRoute,
  MeTrackingRoute: MeTrackingRoute,
  MeWalletRoute: MeWalletRoute,
  MeIndexRoute: MeIndexRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  BudgetRoute: BudgetRoute,
  CampaignsRoute: CampaignsRoute,
  CaptureRoute: CaptureRoute,
  ComplianceRoute: ComplianceRoute,
  ConnectorsRoute: ConnectorsRouteWithChildren,
  CopilotRoute: CopilotRoute,
  DesignSystemRoute: DesignSystemRoute,
  FairnessRoute: FairnessRoute,
  InsightsRoute: InsightsRouteWithChildren,
  KioskRoute: KioskRoute,
  LoginRoute: LoginRouteWithChildren,
  MeRoute: MeRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PayrollRoute: PayrollRoute,
  PeopleRoute: PeopleRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  WhatsappRoute: WhatsappRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  BoardsIdRoute: BoardsIdRoute,
  DashboardHrRoute: DashboardHrRoute,
  DashboardManagerRoute: DashboardManagerRoute,
  DashboardOwnerRoute: DashboardOwnerRoute,
  BoardsIndexRoute: BoardsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  WorkflowsIdRunsRoute: WorkflowsIdRunsRoute,
  WorkflowsIdIndexRoute: WorkflowsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
