/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardHrRouteImport } from './routes/dashboard.hr'
import { Route as DashboardManagerRouteImport } from './routes/dashboard.manager'
import { Route as DashboardOwnerRouteImport } from './routes/dashboard.owner'
import { Route as LoginOtpRouteImport } from './routes/login.otp'
import { Route as MePreferencesRouteImport } from './routes/me.preferences'
import { Route as MeRecognitionsRouteImport } from './routes/me.recognitions'
import { Route as MeRedeemRouteImport } from './routes/me.redeem'
import { Route as MeShoutoutRouteImport } from './routes/me.shoutout'
import { Route as MeTrackingRouteImport } from './routes/me.tracking'
import { Route as MeWalletRouteImport } from './routes/me.wallet'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsIdIndexRouteImport } from './routes/workflows.$id.index'
import { Route as WorkflowsIdRunsRouteImport } from './routes/workflows.$id.runs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHrRoute = DashboardHrRouteImport.update({
  id: '/dashboard/hr',
  path: '/dashboard/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManagerRoute = DashboardManagerRouteImport.update({
  id: '/dashboard/manager',
  path: '/dashboard/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOwnerRoute = DashboardOwnerRouteImport.update({
  id: '/dashboard/owner',
  path: '/dashboard/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOtpRoute = LoginOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => LoginRoute,
} as any)
const MePreferencesRoute = MePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => MeRoute,
} as any)
const MeRecognitionsRoute = MeRecognitionsRouteImport.update({
  id: '/recognitions',
  path: '/recognitions',
  getParentRoute: () => MeRoute,
} as any)
const MeRedeemRoute = MeRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => MeRoute,
} as any)
const MeShoutoutRoute = MeShoutoutRouteImport.update({
  id: '/shoutout',
  path: '/shoutout',
  getParentRoute: () => MeRoute,
} as any)
const MeTrackingRoute = MeTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => MeRoute,
} as any)
const MeWalletRoute = MeWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => MeRoute,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdIndexRoute = WorkflowsIdIndexRouteImport.update({
  id: '/workflows/$id/',
  path: '/workflows/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRunsRoute = WorkflowsIdRunsRouteImport.update({
  id: '/workflows/$id/runs',
  path: '/workflows/$id/runs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/dashboard/hr': typeof DashboardHrRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/login/otp': typeof LoginOtpRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/recognitions': typeof MeRecognitionsRoute
  '/me/redeem': typeof MeRedeemRoute
  '/me/shoutout': typeof MeShoutoutRoute
  '/me/tracking': typeof MeTrackingRoute
  '/me/wallet': typeof MeWalletRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRoute
  '/workflows/$id/': typeof WorkflowsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/dashboard/hr': typeof DashboardHrRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/login/otp': typeof LoginOtpRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/recognitions': typeof MeRecognitionsRoute
  '/me/redeem': typeof MeRedeemRoute
  '/me/shoutout': typeof MeShoutoutRoute
  '/me/tracking': typeof MeTrackingRoute
  '/me/wallet': typeof MeWalletRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRoute
  '/workflows/$id': typeof WorkflowsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRouteWithChildren
  '/me': typeof MeRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/dashboard/hr': typeof DashboardHrRoute
  '/dashboard/manager': typeof DashboardManagerRoute
  '/dashboard/owner': typeof DashboardOwnerRoute
  '/login/otp': typeof LoginOtpRoute
  '/me/preferences': typeof MePreferencesRoute
  '/me/recognitions': typeof MeRecognitionsRoute
  '/me/redeem': typeof MeRedeemRoute
  '/me/shoutout': typeof MeShoutoutRoute
  '/me/tracking': typeof MeTrackingRoute
  '/me/wallet': typeof MeWalletRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRoute
  '/workflows/$id/': typeof WorkflowsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/design-system'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/dashboard/hr'
    | '/dashboard/manager'
    | '/dashboard/owner'
    | '/login/otp'
    | '/me/preferences'
    | '/me/recognitions'
    | '/me/redeem'
    | '/me/shoutout'
    | '/me/tracking'
    | '/me/wallet'
    | '/workflows/'
    | '/workflows/$id/runs'
    | '/workflows/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/design-system'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/dashboard/hr'
    | '/dashboard/manager'
    | '/dashboard/owner'
    | '/login/otp'
    | '/me/preferences'
    | '/me/recognitions'
    | '/me/redeem'
    | '/me/shoutout'
    | '/me/tracking'
    | '/me/wallet'
    | '/workflows'
    | '/workflows/$id/runs'
    | '/workflows/$id'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/design-system'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/dashboard/hr'
    | '/dashboard/manager'
    | '/dashboard/owner'
    | '/login/otp'
    | '/me/preferences'
    | '/me/recognitions'
    | '/me/redeem'
    | '/me/shoutout'
    | '/me/tracking'
    | '/me/wallet'
    | '/workflows/'
    | '/workflows/$id/runs'
    | '/workflows/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRouteWithChildren
  MeRoute: typeof MeRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  DashboardHrRoute: typeof DashboardHrRoute
  DashboardManagerRoute: typeof DashboardManagerRoute
  DashboardOwnerRoute: typeof DashboardOwnerRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  WorkflowsIdRunsRoute: typeof WorkflowsIdRunsRoute
  WorkflowsIdIndexRoute: typeof WorkflowsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/hr': {
      id: '/dashboard/hr'
      path: '/dashboard/hr'
      fullPath: '/dashboard/hr'
      preLoaderRoute: typeof DashboardHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/manager': {
      id: '/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof DashboardManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/owner': {
      id: '/dashboard/owner'
      path: '/dashboard/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof DashboardOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/otp': {
      id: '/login/otp'
      path: '/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof LoginOtpRouteImport
      parentRoute: typeof LoginRoute
    }
    '/me/preferences': {
      id: '/me/preferences'
      path: '/preferences'
      fullPath: '/me/preferences'
      preLoaderRoute: typeof MePreferencesRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/recognitions': {
      id: '/me/recognitions'
      path: '/recognitions'
      fullPath: '/me/recognitions'
      preLoaderRoute: typeof MeRecognitionsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/redeem': {
      id: '/me/redeem'
      path: '/redeem'
      fullPath: '/me/redeem'
      preLoaderRoute: typeof MeRedeemRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/shoutout': {
      id: '/me/shoutout'
      path: '/shoutout'
      fullPath: '/me/shoutout'
      preLoaderRoute: typeof MeShoutoutRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/tracking': {
      id: '/me/tracking'
      path: '/tracking'
      fullPath: '/me/tracking'
      preLoaderRoute: typeof MeTrackingRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/wallet': {
      id: '/me/wallet'
      path: '/wallet'
      fullPath: '/me/wallet'
      preLoaderRoute: typeof MeWalletRouteImport
      parentRoute: typeof MeRoute
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id/': {
      id: '/workflows/$id/'
      path: '/workflows/$id'
      fullPath: '/workflows/$id/'
      preLoaderRoute: typeof WorkflowsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id/runs': {
      id: '/workflows/$id/runs'
      path: '/workflows/$id/runs'
      fullPath: '/workflows/$id/runs'
      preLoaderRoute: typeof WorkflowsIdRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginOtpRoute: typeof LoginOtpRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginOtpRoute: LoginOtpRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface MeRouteChildren {
  MePreferencesRoute: typeof MePreferencesRoute
  MeRecognitionsRoute: typeof MeRecognitionsRoute
  MeRedeemRoute: typeof MeRedeemRoute
  MeShoutoutRoute: typeof MeShoutoutRoute
  MeTrackingRoute: typeof MeTrackingRoute
  MeWalletRoute: typeof MeWalletRoute
}

const MeRouteChildren: MeRouteChildren = {
  MePreferencesRoute: MePreferencesRoute,
  MeRecognitionsRoute: MeRecognitionsRoute,
  MeRedeemRoute: MeRedeemRoute,
  MeShoutoutRoute: MeShoutoutRoute,
  MeTrackingRoute: MeTrackingRoute,
  MeWalletRoute: MeWalletRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRouteWithChildren,
  MeRoute: MeRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  DashboardHrRoute: DashboardHrRoute,
  DashboardManagerRoute: DashboardManagerRoute,
  DashboardOwnerRoute: DashboardOwnerRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  WorkflowsIdRunsRoute: WorkflowsIdRunsRoute,
  WorkflowsIdIndexRoute: WorkflowsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
